name: Deploy to Firebase Hosting
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug Firebase Credentials
        run: |
          if [ -n "${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}" ]; then
            echo "FIREBASE_ADMIN_CREDENTIALS is set. Length: $(echo -n '${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}' | wc -c)"
          else
            echo "FIREBASE_ADMIN_CREDENTIALS is NOT set."
          fi
      - name: Build project
        run: npm run build
        env:
          FIREBASE_ADMIN_CREDENTIALS: ${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}
        
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          projectId: landing-page-astroya
          entryPoint: "."