name: Deploy to Firebase Hosting
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug Firebase Credentials
        run: |
          if [ -n "${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}" ]; then
            SECRET="${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}"
            LENGTH=$(echo -n "$SECRET" | wc -c)
            FIRST_10=$(echo -n "$SECRET" | head -c 10)
            LAST_10=$(echo -n "$SECRET" | tail -c 10)
            echo "FIREBASE_ADMIN_CREDENTIALS is set."
            echo "Length: $LENGTH"
            echo "First 10 chars: $FIRST_10"
            echo "Last 10 chars: $LAST_10"
          else
            echo "FIREBASE_ADMIN_CREDENTIALS is NOT set."
          fi
      - name: Build project
        run: npm run build
        env:
          FIREBASE_ADMIN_CREDENTIALS: ${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}
        
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          projectId: landing-page-astroya
          entryPoint: "."